let productsDB = [
    {
      id: 1,
      image: "./imgs/images/prod-01.png",
      title: "Product-1 title",
      description: "Product-1 description",
      category: "pizza",
      qyt: 1,
      price: 30,
    },
    {
      id: 2,
      image: "./imgs/images/prod-02.png",
      title: "Product-2 title",
      description: "Product-2 description",
      category: "pizza",
      qyt: 1,
      price: 25,
    },
    {
      id: 3,
      image: "./imgs/images/prod-03.png",
      title: "Product-3 title",
      description: "Product-3 description",
      category: "pizza",
      qyt: 1,
      price: 30,
    },
    {
      id: 4,
      image: "./imgs/images/prod-04.png",
      title: "Product-4 title",
      description: "Product-4 description",
      category: "pizza",
      qyt: 1,
      price: 15,
    },
    {
      id: 5,
      image: "./imgs/images/prod-05.png",
      title: "Product-5 title",
      description: "Product-5 description",
      category: "pizza",
      qyt: 1,
      price: 10,
    },
    {
      id: 6,
      image: "./imgs/images/prod-06.png",
      title: "Product-6 title",
      description: "Product-6 description",
      category: "pizza",
      qyt: 1,
      price: 25,
    },
    {
      id: 7,
      image: "./imgs/images/prod-07.png",
      title: "Product-7 title",
      description: "Product-7 description",
      category: "pizza",
      qyt: 1,
      price: 10,
    },
    {
      id: 8,
      image: "./imgs/images/prod-08.png",
      title: "Product-8 title",
      description: "Product-8 description",
      category: "pizza",
      qyt: 1,
      price: 15,
    },
    {
      id: 9,
      image: "./imgs/images/prod-09.png",
      title: "Product-9 title",
      description: "Product-9 description",
      category: "pizza",
      qyt: 1,
      price: 20,
    },
    {
      id: 10,
      image: "./imgs/images/prod-10.jpg",
      title: "Product-10 title",
      description: "Product-10 description",
      category: "pizza",
      qyt: 1,
      price: 15,
    },
  ];
  
  localStorage.setItem("productsDB", JSON.stringify(productsDB));
  